general:
  seed: 0
  task_name: expe1
  device: 0
  nbre_plot: 2

path:
  dimacs_dir: ./data/dataset_10000p/10_40/train/dimacs
  out_dir: ./data/dataset_10000p/10_40/train/pickle
  train_dir: ./data/dataset_10000p/10_40/train/pickle
  val_dir: ./data/dataset_10000p/10_40/val/pickle
  test_dir: ./data/dataset_10000p/10_40/val/pickle
  logs_tensorboard : ./runs/test_1
  model1: ./models/0.95_best.pth.tar
  model2: ./models/0.95_best.pth.tar

generate_data:
  do_it: No
  n_pairs: 100 # nombre de données de train
  min_n: 3 #loi uniforme pour le nombre de varible : nombre min
  max_n: 5 #loi uniforme pour le nombre de varible : nombre min
  max_nodes_per_batch: 1200 #We batched multiple problems together,
                            #with each batch containingup to XXX nodes (i.e.literals plus clauses)
  one: 0 # ?
  p_k_2: 0.7 # parametre pour loi bernouilli selon rmq 2 partie 4 (1-0.7 = 0.3)
  p_geo: 0.4 # parametre pour loi geometric selon rmq 2 partie 4

training:
  n_epochs: 15
  embbeding_dim: 128
  T : 26
  weight_decay: 0.0000000001
  lr: 0.00002
  sparse: No
  l1weight: 0.001
  sparseKL: No
  KL_distribval: 0.1
  initialisation: predict_model #random, predict_model

eval:
  initialisation: random #random, predict_model



