general:
  seed: 0
  task_name: test
  device: 0

path:
  dimacs_dir: ./data/val/dimacs
  out_dir: ./data/val/pickle
  train_dir: ./data/petit_train/pickle
  val_dir: ./data/val/pickle
  test_dir: ./data/test/pickle
  logs_tensorboard : ./runs/test_1
  model: ./runs/test_1test/2020_03_16_15_59_01_297781/0.538135_best.pth.tar

generate_data:
  do_it: No
  n_pairs: 1000 # nombre de données de train
  min_n: 3 #loi uniforme pour le nombre de varible : nombre min
  max_n: 5 #loi uniforme pour le nombre de varible : nombre min
  max_nodes_per_batch: 12000 #We batched multiple problems together,
                            #with each batch containingup to XXX nodes (i.e.literals plus clauses)
  one: 0 # ?
  p_k_2: 0.3 # parametre pour loi bernouilli selon rmq 2 partie 4 (1-0.7 = 0.3)
  p_geo: 0.4 # parametre pour loi geometric selon rmq 2 partie 4

training:
  n_epochs: 10
  embbeding_dim: 128
  T : 26
  weight_decay: 0.0000000001
  lr: 0.00002
  sparse: yes
  sparseKL: No
  l1weight: 0.001


